### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ker0olos** [fable-community/packs#1]
```[tasklist]
### Tasks
- [ ] https://github.com/fable-community/packs/issues/19
- [ ] https://github.com/fable-community/packs/issues/25
- [ ] https://github.com/fable-community/packs/issues/13
- [ ] https://github.com/fable-community/packs/issues/11
```
